//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yiim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int ID { get; set; }
        public int UserRoleId { get; set; }
        public int FunctionalityId { get; set; }
    
        public virtual UserFunctionality UserFunctionality { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
