//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yiim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFunctionality
    {
        public UserFunctionality()
        {
            this.UserPermissions = new HashSet<UserPermission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
    }
}
