//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yiim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserToUserRoles = new HashSet<UserToUserRole>();
        }
    
        public int Id { get; set; }
        public string RealName { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Email { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<UserToUserRole> UserToUserRoles { get; set; }
    }
}
