//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yiim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.UserPermissions = new HashSet<UserPermission>();
            this.UserToUserRoles = new HashSet<UserToUserRole>();
        }
    
        public int ID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<UserToUserRole> UserToUserRoles { get; set; }
    }
}
